export const endpoints = {
    auth: {
        login: 'admin/auth/token',
    },
    categories: {
        list: 'admin/categories/',
        create: 'admin/categories/',
        update: (id: number | string) => `admin/categories/${id}`,
        delete: (id: number | string) => `admin/categories/${id}`,
        getById: (id: number | string) => `admin/categories/${id}`,
    },
    suppliers: {
        list: 'admin/suppliers/',
        create: 'admin/suppliers/',
        update: (id: number | string) => `admin/suppliers/${id}`,
        delete: (id: number | string) => `admin/suppliers/${id}`,
        getById: (id: number | string) => `admin/suppliers/${id}`,
    },
    leads: {
        list: (leadType: string) => `admin/quotes-inquiries/${leadType}`,
        create: 'admin/leads/',
        update: (id: number | string) => `admin/leads/${id}`,
        delete: (id: number | string) => `admin/leads/${id}`,
        getById: (id: number | string) => `admin/leads/${id}`,
    },
    products: {
        list: 'admin/products/',
        create: 'admin/products/',
        update: (id: number | string) => `admin/products/${id}`,
        delete: (id: number | string) => `admin/products/${id}`,
        getById: (id: number | string) => `admin/products/${id}`,
        kpis: 'admin/products/product-kpis',
    },
    countries: {
        list: 'admin/countries/',
        create: 'admin/countries/',
        update: (id: number | string) => `admin/countries/${id}`,
        delete: (id: number | string) => `admin/countries/${id}`,
        getById: (id: number | string) => `admin/countries/${id}`,
    },
    supplierTypes: {
        list: 'admin/supplier-types/',
        create: 'admin/supplier-types/',
        update: (id: number | string) => `admin/supplier-types/${id}`,
        delete: (id: number | string) => `admin/supplier-types/${id}`,
        getById: (id: number | string) => `admin/supplier-types/${id}`,
    },
    productTypes: {
        list: 'admin/product-types/',
        create: 'admin/product-types/',
        update: (id: number | string) => `admin/product-types/${id}`,
        delete: (id: number | string) => `admin/product-types/${id}`,
        getById: (id: number | string) => `admin/product-types/${id}`,
    },
}